name: CI

on:
  pull_request:

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    name: PR Checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Run ruff check (linting)
        run: |
          uv run ruff check .

      - name: Run ruff format (formatting check)
        run: |
          uv run ruff format --check .

      - name: Run tests
        run: |
          uv run pytest tests/
