name: Post Attendance
on:
  schedule:
    - cron: '24 17 * * *' # Runs every day at 17:24 UTC
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use'
        required: false
        default: 'main'
        type: choice
        options:
          - main
          - test
jobs:
  post-attendance:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'main' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Install dependencies
        run: |
          uv sync
      - name: Run Post Attendance Script
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          ATTENDANCE_CHANNEL_ID: ${{ secrets.ATTENDANCE_CHANNEL_ID }}
        run: |
          uv run src/archer/scripts/post_attendance.py